export const ADD_DIVERS = "ADD_DIVERS";
export const DIVERS_LOADING = "DIVERS_LOADING";
export const DIVERS_FAILED = "DIVERS_FAILED";
export const PRESENCE_DIVERS = "PRESENCE_DIVERS";
export const CAN_DIVE_DIVERS = "CAN_DIVE_DIVERS";
export const UPDATE_DIVERS_STAT = "UPDATE_DIVERS_STAT"

export const ADD_TRACKS = "ADD_TRACKS";
export const TRACKS_LOADING = "TRACKS_LOADING";
export const TRACKS_FAILED = "TRACKS_FAILED";

export const TRACKS_PERSONS = "TRACKS_PERSONS";
export const UPDATE_TRACKS_PERSONS = "UPDATE_TRACKS_PERSONS"